### NumPy
Library Aljabar Linear for Python<br>
sangat cepat krna dibangun dengan bahasa C

In [1]:
import numpy as np

In [2]:
angka = [1,2,3,4]

In [4]:
angkanp = np.array([1,2,3,4,5])

In [8]:
angka*3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [9]:
angkanp*3

array([ 3,  6,  9, 12, 15])

In [16]:
list_angka = ([1,2,3],[4,5,6],[7,8,9])

In [17]:
list_angkanp = np.array(list_angka)
list_angkanp

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(1,30,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29])

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.linspace(0,8,10) # 0 awal 8 akhir, 10 dipecah menjadi 10 bagian

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

#### Identity Matrix
Elemen yang i=j (indeks baris dan indeks kolom sama) adalah 1 dan sisanya 0, seperti:

In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

#### np.diag
dapat mendefinisikan array 2D persegi dengan nilai tertentu di sepanjang diagonalnya atau jika diberikan array 2D akan mengembalikan array 1D yang hanya berupa elemen diagonal. Dua fungsi pembuatan array dapat berguna saat mengerjakan aljabar linier, seperti:

In [36]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [40]:
np.diag([1,2,3],1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [45]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [46]:
np.diag(a)

array([1, 4])