### Operasi Matematika di Numpy

In [42]:
import numpy as np

In [43]:
angka = np.arange(0,11)

In [44]:
angka

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
angka+5 #dijumlahkan 0+5,1+5 dst

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [47]:
angka+angka #dijumlahkan dengan dirinya sendiri 1+1 2+2 3+3 dst

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [48]:
list_angka = [1,2,3,4,5]

In [49]:
list_angka+list_angka

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [50]:
angka*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [51]:
list_angka*3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [52]:
angka

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
angka-angka

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
angka-10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [55]:
1/0 #karena dibagi 0 akan error

ZeroDivisionError: division by zero

In [56]:
angka/angka

C:\Users\renal\AppData\Local\Temp\ipykernel_13048\2282081036.py:1: RuntimeWarning: invalid value encountered in divide
  angka/angka


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [57]:
1/angka

C:\Users\renal\AppData\Local\Temp\ipykernel_13048\4117288803.py:1: RuntimeWarning: divide by zero encountered in divide
  1/angka


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [58]:
np.sqrt(angka)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [60]:
np.exp(angka)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

## e = 2.7182

In [61]:
np.max(angka)

10

In [62]:
np.min(angka)

0

In [63]:
np.sin(angka)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [65]:
np.cos(angka)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [66]:
np.tan(angka)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])

In [67]:
np.log(angka)

C:\Users\renal\AppData\Local\Temp\ipykernel_13048\2456787053.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(angka)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [68]:
np.log10(angka)

C:\Users\renal\AppData\Local\Temp\ipykernel_13048\4170947744.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(angka)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251,
       1.        ])

In [69]:
# belajar case study lebih baik, jika ada operasi matematika bisa lihat di numpy.org/reference